### ISSUE TITLE
Missing "Priority" in alertmanager notifications

### ISSUE THREAD

**Issue by mac-chaffee** [falcosecurity/falcosidekick#275]
**Motivation**

When Falco sends alertmanager an alert, it looks like it doesn't include the "priority" field:
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/7581860/136609601-a8eeed58-55ae-4984-a51b-040fa95b25fc.png">

That makes it difficult to route alerts to the right "receivers". For example, I'd like to send "warning" alerts to one notification system and "emergency|alert|critical|error" alerts to a different notification system that is more closely monitored.

**Feature**

Include the "priority" field in the alertmanager payload as a "label".

**Alternatives**

Other alerts like the ones that ship with [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) use a label called "severity" instead of "priority". That could be an option, but "priority" is probably better for consistency with the rest of falco.

**Comment by Issif** [comment]
Hello, you're right, I missed that, sorry. See [alertmanager.go#L77](https://github.com/falcosecurity/falcosidekick/blob/01b5d4eeee99950a3f611b9bfbc4ce08870d3ec7/outputs/alertmanager.go#L77).

It's not a big deal to add this, feel free to propose a PR for fixing it if you feel confident enough. Anyway, I'm planning to work soon on all outputs for adding `tags` (which are now included in events since falco 0.30.0), I may fix that too.

Thanks for the issue, it will help everybody.
